'''
Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''
def solve():
    answer = 0
    val1 = 0
    val2 = 1
    tempVal = 0

    while val2 <= 4000000:
        if (val2%2==0):
            answer = answer + val2
        tempVal = val2
        val2 = val1 + tempVal
        val1 = tempVal

    print(answer)

if __name__ == "__main__":
    solve()
